SET SERVEROUTPUT ON;
DECLARE
  V_LOC STATION.LOCATN%TYPE:='&Enter_Station_Name';
  V_NO_STANDS INTEGER:='&Enter_Number_Of_Stands';
  
  -- DECLARE CURRENT DETAILS CURSOR
  CURSOR READY_BIKES
  IS
    SELECT BikeID
    FROM Bike
    WHERE STATUS LIKE 'R';
    
  CURSOR LOC_STANDS
  IS 
    SELECT * 
    FROM STAND
    WHERE location LIKE V_LOC;
  
  --INITIALISE CURRENT CURSOR AS CUR_CURRENT_DETAILS
  V_THIS_BIKE BIKE.BIKEID%TYPE;
  THIS_STAND LOC_STANDS%ROWTYPE;
  V_MAX INTEGER;
  
BEGIN
  OPEN READY_BIKES;
  OPEN LOC_STANDS;
  
  IF READY_BIKES%ROWCOUNT < V_NO_STANDS THEN
    V_MAX := READY_BIKES%ROWCOUNT;
    
  ELSE
    V_MAX := V_NO_STANDS;
  
  FOR I IN 1 .. V_MAX
  LOOP 
    
    FETCH READY_BIKES INTO V_THIS_BIKE;
    FETCH LOC_STANDS INTO THIS_STAND;
    UPDATE STAND
    SET BIKEID = V_THIS_BIKE
    WHERE LOCATN = V_LOC AND 
    L_OFFSET = I;
    
  END LOOP;
  
  CLOSE READY_BIKES;
  CLOSE LOC_STANDS;
  
EXCEPTION
  WHEN OTHERS THEN
    DMBS_OUTPUT.PUT_LINE('ERROR, YOU THICK FUCK!');
    
END;