SET SERVEROUTPUT ON;
DECLARE
  V_LOC STATION.LOCATN%TYPE:='&Enter_Station_Name';
  V_NO_STANDS INTEGER:='&Enter_Number_Of_Stands';
  
BEGIN
  INSERT INTO STATION (locatn) VALUES (V_LOC);
  
  FOR I IN 1 .. V_NO_STANDS
  LOOP
    INSERT INTO STAND (locatn, L_Offset, Status)
    VALUES (V_LOC, I, 'F');
  END LOOP;
  COMMIT;

EXCEPTION
  WHEN OTHERS THEN
    DMBS_OUTPUT.PUT_LINE('ERROR, YOU THICK FUCK!');
    

END;