CREATE OR REPLACE TRIGGER LOG_TEAM_TRIGGER
AFTER INSERT ON TEAMS 
FOR EACH ROW 
BEGIN  
	INSERT INTO LOGTEAM VALUES(:NEW.TeamName, SYSDATE);

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No data found');
    
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error code: '||SQLCODE||' means '||SQLERRM);
END LOG_TEAM_TRIGGER;