CREATE OR REPLACE TRIGGER EUROPA_TEAM_TRIGGER
AFTER INSERT ON TEAMS 
FOR EACH ROW

DECLARE
  ExistingTeamCount integer;
  
BEGIN
  SELECT COUNT(*) INTO ExistingTeamCount 
  FROM EUROLEAGUE WHERE TeamName = :NEW.TeamName;
  
  IF ExistingTeamCount = 0 THEN
    INSERT INTO EUROLEAGUE VALUES(:NEW.TeamName,0,0,0,0);
  END IF;
  
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('No data found');
    
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error code: '||SQLCODE||' means '||SQLERRM);
END EUROPA_TEAM_TRIGGER;