SELECT * FROM MEMBER;
SELECT * FROM EQUIPMENTTYPE;
SELECT * FROM ITEMFORLOAN;
SELECT * FROM LOAN;

--QUESTION 1
SELECT UNIQUE mname 
FROM MEMBER
JOIN LOAN USING (memberid)
JOIN ITEMFORLOAN USING (serialno)
JOIN EQUIPMENTTYPE USING (brandname)
WHERE brandname LIKE 'Apple';

--QUESTION 2
SELECT mname, brandname, count(*)
FROM MEMBER
JOIN LOAN USING (memberid)
JOIN ITEMFORLOAN USING (serialno)
JOIN EQUIPMENTTYPE USING (brandname)
GROUP BY mname, brandname HAVING COUNT(*) > 1;

--QUESTION 3
SELECT brandname 
FROM EQUIPMENTTYPE
MINUS
SELECT brandname
FROM ITEMFORLOAN;

--QUESTION 4
SELECT mname 
FROM MEMBER
JOIN LOAN USING (memberid)
JOIN ITEMFORLOAN USING (serialno)
WHERE brandname LIKE '%iPad%'
MINUS
SELECT mname 
FROM MEMBER
JOIN LOAN USING (memberid)
JOIN ITEMFORLOAN USING (serialno)
WHERE brandname LIKE '%Watch%';

--QUESTION 5
SELECT mname 
FROM MEMBER
JOIN LOAN USING (memberid)
JOIN ITEMFORLOAN USING (serialno)
WHERE brandname LIKE '%iPad%'
INTERSECT
SELECT mname 
FROM MEMBER
JOIN LOAN USING (memberid)
JOIN ITEMFORLOAN USING (serialno)
WHERE brandname LIKE '%Watch%';

--QUESTION 6
SELECT mname
FROM MEMBER
WHERE NOT EXISTS
  (SELECT *
  FROM EQUIPMENTTYPE
  WHERE (EQCOMPANY LIKE 'Dell') AND NOT EXISTS
    (SELECT *
    FROM LOAN
    JOIN ITEMFORLOAN USING (serialno)
    WHERE (LOAN.memberid = MEMBER.memberid)
    AND (EQUIPMENTTYPE.brandname  = ITEMFORLOAN.brandname)
    )
  );
  
--QUESTION 7
SELECT mname, (costpernight * (SYSDATE - duedate)) as FEE
FROM MEMBER
JOIN LOAN USING (memberid)
JOIN ITEMFORLOAN USING (serialno)
JOIN EQUIPMENTTYPE USING (brandname)
WHERE returndate is NULL;
