//Encapsulstion
//Inheritance
//Polymorphism

/* GIT*/
/*
  GIT COMMIT 
  - COMMIT EVERYTIME YOU UPDATE OR CHANGE YOUR CODE EVERY 30 MINS
  - COMMIT SNAPSHOTS
  - MERGES CHANGES MADE BY TWO PEOPLE (IF NO CONFLICT)
  
  GIT BRANCH
  - BRANCH OF FROM A VERSION OF YOUR CODE TO TRY NEW FEATURES 
  - MASTER BRANCH: MAIN BRANCH YOU COMMIT TO
  
  GIT CLIENTS
  - GIT BASH RECOMENDED
  - GIT FOR WINDOWS
  
  GIT HUB
  - SERVER TO BACK UP CODE
  - NEED TO MAKE EVERYTHING PUBLIC
  
  GIT ACADEMIC
  - USED TO CREATE PRIVATE REPS
  
  BIT BUCKET
  - PRIVATE REPS FOR SMALL TEAMS
  
  TIPS
  - WHEN CREATING A REP TYPE A DESCRIPTION
  - INCLUDE A GIT IGNORE FILE (TAKES ONLY FILES YOU WANT)
  - INITIALISE THE REP WITH A READ ME
  - MIT LISCENCE SO YOU CAN BE GIVEN CREDIT IF OTHERS USE YOUR CODE
*/

/* GIT COMMANDS */
/*
  PWD - CHECK CURRENT DIRECTORY
  CD "Folder Name" - CHANGE INTO FOLDER
  ls - SHOW ALL FILES IN A FOLDER
  
  ---BASIC COMMANDS ---
  
  git clone url - COPY EVRYTHING FROM A GIT REP TO A FOLDER YOU ARE IN 
  git init - INITILASE GIT REP INSIDE A FOLDER
  git remote add origin URL - LINKS SERVER AND LOCAL FOLDER
  //ORIGIN MUST ALWAYS BE SETUP 
  //SHIFT + INSERT ON WINDOS TO PASTE IN BASH 
  
  git pull origin master - COPY FILES FROM SERVER TO LOCAL MAIN BRANCH FOLDER
  git add . - ADD ALL FILES IN FOLDER RECURSIVLEY TO TEMP AREA READY TO UPLOAD
  git commit -m "Your Message" - COMMIT YOUR FILES (-m TO ADD A MESSAGE)
  git push --set-upstream origin master - LINKS MASTER FOLDERS (only first time)
  git push - PUSH YOUR CODE TO THE SERVER 
  git log - SHOWS HISTORY OF THE BRANCH YOU ARE IN
  
  --- ADVANCED COMMANDS ---
  
  //GOING BACK TO AN OLD VERSION? NEED 40 DIGIT COMMIT NUMBER
  git checkout NUM - GO BACK TO OLDER VERSION
  git checkout master - BRING YOU TO THE NEWEST VERSION
  git branch NAME - CREATES A NEW BRANCH 
  git btanch -b NAME - CREATES NEW BRANCH AND SWITCHES TO IT
  git merge NAME - MERGES BRANCH "NAME" with whatever branch you are in
  
*/

void setup()
{
  size(500, 500);
}//end setup 

void draw()
{
  text("Hello GIT", 100, 100); 
}
