package Fragments;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.Resources;
import android.database.Cursor;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import android.widget.Toast;

import com.example.danieltilley.time2work.R;

import DAO.DBManager;

/**
 * Created by danieltilley on 17/11/2016.
 */

//This fragment class is responsible for displaying the total
public class TotalForMonth extends Fragment {

    //Text Views
    private TextView titleText;
    private TextView hourText;
    private TextView minsText;
    private TextView daysText;
    private TextView amountEarnedText;

    //calculation variables (used in getDetails() method)
    private int totalHours = 0;
    private int totalMinutes = 0;
    private int totalDays = 0;
    private float amountEarned = .00f;
    private String amountEarnedString = "€0";

    //Other variables
    private DBManager db; //db manager
    private Intent receiveIntent; //intent that we arrived from
    private String position; //month key (used for db query)
    private Cursor cursor; //cursor that is populated with data from db

    private View rootView; //view generated by Fragment
    private Activity referenceActivity; //reference for methods which require an activity

    //Shared preferences variables
    private String USER_PREFS_NAME;
    private String PREFS_KEY_HOURLY_RATE;
    private final String PREFS_KEY_NOT_FOUND = "Not found";
    SharedPreferences UserPrefs; //shared preferences object
    SharedPreferences.Editor editor; //shared prefs editor


    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        rootView = inflater.inflate(R.layout.fragment_total_hours_display, container, false);

        initialise();
        getCertainEvents();
        setAllText();

        return rootView;
    }//end on create view


    public void initialise(){
        referenceActivity = getActivity();

        titleText = (TextView) rootView.findViewById(R.id.fragment_display_total_title);
        hourText = (TextView) rootView.findViewById(R.id.textView_fragment_display_total_hours);
        minsText = (TextView) rootView.findViewById(R.id.textView_fragment_display_total_mins);
        daysText = (TextView) rootView.findViewById(R.id.textView_fragment_display_total_days);
        amountEarnedText = (TextView) rootView.findViewById(R.id.textView_fragment_display_total_amount_earned);
        db = new DBManager(getContext());

        receiveIntent = referenceActivity.getIntent();
        position = receiveIntent.getStringExtra("MONTH_KEY");

        //Shared preferences
        USER_PREFS_NAME = this.getString(R.string.user_prefs_file); //shared preferences file
        PREFS_KEY_HOURLY_RATE = this.getString(R.string.user_prefs_hourly_rate_key);
        UserPrefs = referenceActivity.getSharedPreferences(USER_PREFS_NAME, 0);
        editor = UserPrefs.edit();
    }//end initialise


    //method to get events from db
    public void getCertainEvents(){
        try{
            db.open();
            cursor = db.getCertainMonths(position);
            db.close();
        }//end try

        catch (Exception e){
            Toast.makeText(getContext(),R.string.toast_db_error,Toast.LENGTH_SHORT).show();
        }//end catch
    }//end getCertainEvents


    public void setAllText(){
        //method to get necessary info to populate textViews
        getDetails();

        //Variables as concatenation can't be done in setText()
        String titleString = "For " + getMonth();
        String hoursString = "Total hours worked: " + totalHours;
        String minsString = "Total minutes worked: " + totalMinutes;
        String daysString = "Total days worked: " + totalDays;
        String amountEarnedStringLocal = "Total amount earned (before tax): " + amountEarnedString;

        //set text to strings
        titleText.setText(titleString);
        hourText.setText(hoursString);
        minsText.setText(minsString);
        daysText.setText(daysString);
        amountEarnedText.setText(amountEarnedStringLocal);
    }//end setAllText


    public String getMonth (){
        //Must parse key received from previous screen
        String getMonthKey = position.substring(0,2);

        //get months array stored in string file
        Resources resources = getResources();
        String[] months = resources.getStringArray(R.array.Months);

        //declare month string to be returned and set as the title
        String month = "";

        //switch statement to decide what month to pick from
        switch (getMonthKey){
            case "01":{
                month = months[0];
                break;
            }//end case

            case "02":{
                month = months[1];
                break;
            }//end case

            case "03":{
                month = months[2];
                break;
            }//end case

            case "04":{
                month = months[3];
                break;
            }//end case

            case "05":{
                month = months[4];
                break;
            }//end case

            case "06":{
                month = months[5];
                break;
            }//end case

            case "07":{
                month = months[6];
                break;
            }//end case

            case "08":{
                month = months[7];
                break;
            }//end case

            case "09":{
                month = months[8];
                break;
            }//end case

            case "10":{
                month = months[9];
                break;
            }//end case

            case "11":{
                month = months[10];
                break;
            }//end case

            case "12":{
                month = months[11];
                break;
            }//end case
        }//end switch

        return month;
    }//end get month


    //method for getting all info to populate TextViews
    public void getDetails(){

        String lastDate = ""; //used when checking dates

        //loop through cursor
        if (cursor.moveToFirst()) {
            do {
                //check for matching dates
                if (!(cursor.getString(cursor.getColumnIndexOrThrow(getString(R.string.events_db_date_column_name))).equals(lastDate))){
                    totalDays++;
                }//end if

                totalMinutes += cursor.getInt(cursor.getColumnIndexOrThrow(getString(R.string.events_db_total_mins_column_name)));
                totalHours += cursor.getInt(cursor.getColumnIndexOrThrow(getString(R.string.events_db_total_hours_column_name)));

                //check if mins graeter than 59
                if (totalMinutes > 59){
                    totalHours += 1;
                    totalMinutes = totalMinutes - 60;
                }//end if

                //set total amount earned
                //set lastDate to previous date for next check
                lastDate = cursor.getString(cursor.getColumnIndexOrThrow(getString(R.string.events_db_date_column_name)));

            } while (cursor.moveToNext());

            //get hourly rate from shared prefs file
            Float hourlyRate  = Float.parseFloat(UserPrefs.getString(PREFS_KEY_HOURLY_RATE,PREFS_KEY_NOT_FOUND));
            Float minuteRate = hourlyRate / 60; //use minute rate in case extra minutes are there

            //Calculate amount earned and check for extra mins
            amountEarned = hourlyRate * totalHours;

            if (totalMinutes > 0){
                amountEarned += (totalMinutes * minuteRate);
            }//end if

            amountEarnedString = "€";
            amountEarnedString += String.format("%.02f", amountEarned);
        }//end if
    }//end get details


    //resets info to stop bugs
    public void resetInfo(){
        totalHours = 0;
        totalMinutes = 0;
        totalDays = 0;
        amountEarned = 0.00f;
        amountEarnedString = "€0";
    }//end resetInfo


    @Override
    public void onResume() {
        super.onResume();
        resetInfo();
        getCertainEvents();
        setAllText();
    }//end onResume
}//end TotalForMonth fragment class
